### ISSUE TITLE
下载的vbp工程打开时报错

### ISSUE THREAD

**Issue by yonkerzhang** [imxcstar/vb6-miniblink-SBrowser#4]
错误提示为SBrowser.ctl，MiniblinkAPI.cls等文件无法加载，日志文件如下:
不能加载 '0'
行 0: 不能加载文件 D:\vb6-miniblink-SBrowser-master\Ctl\SBrowser.ctl 。
经过对比发现，是因为这些文件是Unix格式的，用ultraEdit转换为dos格式文件就可以正常打开了

**Comment by imxcstar** [comment]
用git指令克隆下载就没问题了
