### ISSUE TITLE
代码编译不通过

### ISSUE THREAD

**Issue by gujin162** [imxcstar/vb6-miniblink-SBrowser#7]
Public Sub jsBindFunction(ByVal name As String, ByVal fn As Long, ByVal argCount As Long)
    Dim TAddress As Long: TAddress =这里是乱码
    SDLL.CallFunction_DLL NodeDllPath, api_jsBindFunction, STR_ANSI, CR_None, CC_CDECL, name, TAddress, argCount
End Sub

**Comment by imxcstar** [comment]
用户git clone把工程克隆下来编译
