### ISSUE TITLE
关于POST下载的问题

### ISSUE THREAD

**Issue by cdz1980** [imxcstar/vb6-miniblink-SBrowser#8]
老师，wkeDownloadCallback已经能够获取下载的链接，但如果是用POST方式下载的，无法获取相应的数据，能否修复？
https://blog.csdn.net/chen249191508/article/details/90264893有一篇文章【解决miniblink 回调函数 on_wkeDownload2Callback 返回值为kWkeDownloadOptCacheData 程序异常】
不知道VB6能实现吗？

**Comment by imxcstar** [comment]
这个要修改mb的代码并且重新编译，你可以把node.dll替换成最新版本的，看看mb官方有没有修复这个问题

**Comment by cdz1980** [comment]
多谢老师回复，最新的node.dll仍然是同样的情况，已问过扫地僧，说是免费版本不支持POST的下载，只能使用VIP版本,mb.exe,但是这个VB6使用不了，太可惜了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"imxcstar"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 晚上6:49
收件人:&nbsp;"imxcstar/vb6-miniblink-SBrowser"<vb6-miniblink-SBrowser@noreply.github.com&gt;;
抄送:&nbsp;"逍遥 "<1393131921@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [imxcstar/vb6-miniblink-SBrowser] 关于POST下载的问题 (#8)




这个要修改mb的代码并且重新编译，你可以把node.dll替换成mb最新版本，看看mb官方有没有修复这个问题

**Comment by imxcstar** [comment]
> 多谢老师回复，最新的node.dll仍然是同样的情况，已问过扫地僧，说是免费版本不支持POST的下载，只能使用VIP版本,mb.exe,但是这个VB6使用不了，太可惜了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"imxcstar"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月9日(星期四) 晚上6:49 收件人:&nbsp;"imxcstar/vb6-miniblink-SBrowser"<vb6-miniblink-SBrowser@noreply.github.com&gt;; 抄送:&nbsp;"逍遥 "<1393131921@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [imxcstar/vb6-miniblink-SBrowser] 关于POST下载的问题 (#8) 这个要修改mb的代码并且重新编译，你可以把node.dll替换成mb最新版本，看看mb官方有没有修复这个问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

其实你可以修改mb的免费版代码，然后重新编译

**Comment by cdz1980** [comment]
网上有一个其他人重新编译过的版本，不过比较早了，BUG应该比较多吧，另外该DLL在VB6里怎么调用on_wkeDownload2Callback，能否指点一下？


https://blog.csdn.net/chen249191508/article/details/90264893 这篇文单写的是C#，我不知道怎么在您写的OCX控件中修改能调用on_wkeDownload2Callback




https://download.csdn.net/download/chen249191508/11182403&nbsp; 这是他人编译修改后DLL下载地址，比较大，邮件无法直接发送给您

**Comment by imxcstar** [comment]
> 网上有一个其他人重新编译过的版本，不过比较早了，BUG应该比较多吧，另外该DLL在VB6里怎么调用on_wkeDownload2Callback，能否指点一下？ https://blog.csdn.net/chen249191508/article/details/90264893 这篇文单写的是C#，我不知道怎么在您写的OCX控件中修改能调用on_wkeDownload2Callback https://download.csdn.net/download/chen249191508/11182403&nbsp; 这是他人编译修改后DLL下载地址，比较大，邮件无法直接发送给您

你在Bas/MiniblinkAPIConst.bas和Cls/MiniblinkAPI.cls添加wkeOnDownload2，然后在Cls/MiniblinkCallBack.cls添加wkeDownload2Callback，然后把那个node.dll替换上去就好了。可以参考wkeOnDownload的代码，你参照那篇csdn的文章确定下参数就好了

**Comment by cdz1980** [comment]
多谢老师，我试一下，&nbsp;wkeDownloadCallback = zb_AddressOf(9, 3, 8)&nbsp; 这一行改成wkeDownload2Callback应该怎么写呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"imxcstar"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 上午10:15
收件人:&nbsp;"imxcstar/vb6-miniblink-SBrowser"<vb6-miniblink-SBrowser@noreply.github.com&gt;;
抄送:&nbsp;"逍遥 "<1393131921@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [imxcstar/vb6-miniblink-SBrowser] 关于POST下载的问题 (#8)



 
网上有一个其他人重新编译过的版本，不过比较早了，BUG应该比较多吧，另外该DLL在VB6里怎么调用on_wkeDownload2Callback，能否指点一下？ https://blog.csdn.net/chen249191508/article/details/90264893 这篇文单写的是C#，我不知道怎么在您写的OCX控件中修改能调用on_wkeDownload2Callback https://download.csdn.net/download/chen249191508/11182403&nbsp; 这是他人编译修改后DLL下载地址，比较大，邮件无法直接发送给您
  
你在Bas/MiniblinkAPIConst.bas和Cls/MiniblinkAPI.cls添加wkeOnDownload2，然后在Cls/MiniblinkCallBack.cls添加wkeDownload2Callback，然后把那个node.dll替换上去就好了。可以参考wkeOnDownload的代码，你参照那篇csdn的文章确定下参数就好了

**Comment by imxcstar** [comment]
> 多谢老师，我试一下，&nbsp;wkeDownloadCallback = zb_AddressOf(9, 3, 8)&nbsp; 这一行改成wkeDownload2Callback应该怎么写呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"imxcstar"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月10日(星期五) 上午10:15 收件人:&nbsp;"imxcstar/vb6-miniblink-SBrowser"<vb6-miniblink-SBrowser@noreply.github.com&gt;; 抄送:&nbsp;"逍遥 "<1393131921@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [imxcstar/vb6-miniblink-SBrowser] 关于POST下载的问题 (#8) 网上有一个其他人重新编译过的版本，不过比较早了，BUG应该比较多吧，另外该DLL在VB6里怎么调用on_wkeDownload2Callback，能否指点一下？ https://blog.csdn.net/chen249191508/article/details/90264893 这篇文单写的是C#，我不知道怎么在您写的OCX控件中修改能调用on_wkeDownload2Callback https://download.csdn.net/download/chen249191508/11182403&nbsp; 这是他人编译修改后DLL下载地址，比较大，邮件无法直接发送给您 你在Bas/MiniblinkAPIConst.bas和Cls/MiniblinkAPI.cls添加wkeOnDownload2，然后在Cls/MiniblinkCallBack.cls添加wkeDownload2Callback，然后把那个node.dll替换上去就好了。可以参考wkeOnDownload的代码，你参照那篇csdn的文章确定下参数就好了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你看一下zb_AddressOf函数的注释说明和参考下其它函数哇，有顺序的，从代码最后一个函数开始数

**Comment by cdz1980** [comment]
imxcstar老师，miniblink有下载和打印的功能，如果把它搬到VB6中，大约多少钱能完成呢

**Comment by ronaldcamacho** [comment]
I cant download this link 
https://download.csdn.net/download/chen249191508/11182403 
Can you upload in other site thank very much
